# Generated by Django 3.0.2 on 2020-03-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatekey',
            name='noSep',
            field=models.CharField(blank=True, default='', max_length=19),
        ),
    ]
