# Generated by Django 3.0.2 on 2020-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200316_1504'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sep',
            old_name='key',
            new_name='nomorsep',
        ),
        migrations.AddField(
            model_name='sep',
            name='nomorsuratkontrol',
            field=models.CharField(default='', max_length=6),
        ),
    ]
