# Generated by Django 3.0.2 on 2020-03-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_generatekey_nosep'),
    ]

    operations = [
        migrations.CreateModel(
            name='noSep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noSep', models.CharField(blank=True, default='', max_length=19)),
            ],
        ),
        migrations.RemoveField(
            model_name='generatekey',
            name='noSep',
        ),
    ]
