# Generated by Django 3.0.2 on 2020-03-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200316_1457'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='noSep',
            new_name='Sep',
        ),
        migrations.RenameField(
            model_name='sep',
            old_name='noSep',
            new_name='key',
        ),
    ]
